### ISSUE TITLE
Electron App - Uncaught Error: The specified module could not be found

### ISSUE THREAD

**Issue by aniruddhashevle** [xxoo/node-fswin#22] opened 2019-09-06 01:52 UTC
**npm version: 6.11.3
node version: 12.3.1
electron version: 5.0.2
winston version: 3.2.1
fswin: 3.18.918
OS: Windows**

This is **run time error occurred** while running the **Electron Desktop App on Windows**.

<img width="818" alt="Screenshot 2019-09-06 at 9 47 24 AM" src="https://user-images.githubusercontent.com/20954198/64395191-f3279580-d08b-11e9-833a-49c8fe95e50f.png">

**Comment by xxoo** [comment] 2019-09-08 14:21
thanks for reporting. the problem is caused by my build settings and some change since electron v4.
anyway it should be fixed by now. please update fswin and try again.
i'm closing this issue. feel free to continue discussing

**Closed by xxoo** 2019-09-08 14:21 UTC
